SHELL := /usr/bin/env bash

NAME := krypton
NAMESPACE =
IMAGE_TAG =
SUFFIX =

SECRET_FILE = values-$(NAMESPACE)$(if $(strip $(SUFFIX)),-$(strip $(SUFFIX))).secret.yaml

ifndef NAME
    $(error NAME is not set)
endif
ifndef NAMESPACE
    $(error NAMESPACE is not set)
endif
ifndef IMAGE_TAG
    $(error IMAGE_TAG is not set)
endif

define arguments
    "${NAME}" . \
    -n "${NAMESPACE}" \
    -f values.yaml \
    -f "${SECRET_FILE}" \
    --set app.image.tag="${IMAGE_TAG}"
endef

.PHONY: helm-dep install upgrade lint uninstall template force-install help

helm-dep:
	helm dependency update

install: helm-dep
	@helm install $(call arguments)

upgrade: helm-dep
	@helm upgrade --install $(call arguments)

lint: helm-dep
	@helm lint . -f values.yaml -f "${SECRET_FILE}" --set app.image.tag="${IMAGE_TAG}"

uninstall:
	@helm uninstall ${NAME} -n ${NAMESPACE}

template: helm-dep
	@helm template $(call arguments) > template.yaml

force-install: uninstall install

help:
	@echo "Available targets:"
	@echo "  install        Install the Helm chart"
	@echo "  upgrade        Upgrade or install the Helm chart"
	@echo "  lint           Dry-run install for validation"
	@echo "  uninstall      Remove the release"
	@echo "  template       Render template to file"
	@echo "  force-install  Uninstall then install"
