{{- $global := .Values.global | default dict -}}
{{- if and .Values.serviceAccount.create (not .Values.serviceAccountName) (not ($global.serviceAccountName | default "")) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "_.serviceAccountName" . }}
  labels:
    {{- include "_.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
